version: "3"
services:
  db:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  backend:
    container_name: tpo_backend
    image: "nikp00/tpo_backend"
    build:
      dockerfile: ../utils/deploy_images/backend/Dockerfile
      context: ../../backend/
    ports:
      - "3000:3000"

  frontend:
    container_name: tpo_frontend
    image: "nikp00/tpo_frontend"
    build:
      dockerfile: ../utils/deploy_images/frontend/Dockerfile
      context: ../../frontend/
    ports:
      - "8080:80"
