version: "3"
services:
  backend:
    container_name: tpo_backend
    image: "nikp00/tpo_backend"
    build:
      dockerfile: ../utils/deploy_images/backend/Dockerfile
      context: ../../backend/

  frontend:
    container_name: tpo_frontend
    image: "nikp00/tpo_frontend"
    build:
      dockerfile: ../utils/deploy_images/frontend/Dockerfile
      context: ../../frontend/